export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const USER_DETAILS_RECEIVED = 'USER_DETAILS_RECEIVED';
export const GET_HEADER = 'GET_HEADER';
export const HEADER_RECEIVED = 'HEADER_RECEIVED';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const COUNTRIES_RECEIVED = 'COUNTRIES_RECEIVED';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILES_RECEIVED = 'PROFILES_RECEIVED';
